### ISSUE TITLE
Lesser visibilty for the Modification date

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#21]
To be honest, I do not understand what is the user story behind the Modification date.

The Creation date is important because it shows when the user has come across this vocabulary for the first time. So listing by it is very useful.

The Modification date is 99% of the time the same as the creation date and in the rest of the cases signifies just a small irrelevant edit. My opinion is that it should be kept in the DB, but not play any role in the UI because it is just distracting.

My two cents...

**Comment by Top-Ranger** [comment]
I personally find the modification date useful, e.g. when you had mistakes in your vocabulary (and in that sense is even more important than the creation date) and you want to include that in your training like new vocabulary.

Where exactly do you find it distracting? Because right now (current development version) it is visible in exactly three places:
* One line in the vocabulary details
* As a filter for training (2 lines)
* As a sort criterium (2 lines)
In my opinion this is just some information useful if you want to use it but not really distracting otherwise.

**Comment by sfbg** [comment]
It is just an opinion and idea on my side. How often would you modify a vocabulary to complete change the translation? 

Reseting the priority after a modification makes sense and that is enough to cover the training.

Perhaps it is better to sort based on a mix of creation and modification date. But in that case, changing the creation date could suffice as well.

Showing the modification date in the word details is useful and not distracting. 

My idea is to keep just relevant functionality. It is not easy to decide what to leave out.

If you do not agree, just close the case and thanks again for the great work.

**Comment by Top-Ranger** [comment]
For now I think the visibility is acceptable, however I'll definitely keep it in mind for further feature updates.

Thanks a loot for your input!
