### ISSUE TITLE
CSV import fails

### ISSUE THREAD

**Issue by Bu33zhidao** [Top-Ranger/harbour-vocabulary#8]
I'm experiencing problems importing *.csv.  Error message is
„INSERT OR ABORT INTO vocabulary VALUES(?;?;?): UNIQUE constraint failed: vocabulary.word Unable to fetch row”
Any hint what's wrong with my *.csv? I can provide it for debugging if you're interested.

**Comment by Top-Ranger** [comment]
The problem is that you are trying to import vocabularies which are already in your database (as determined by the 'word' of the vocabulary). The wording there might be a bit bad...

I'm currently working on a way where you can automatically replace such vocabulary. This will hopefully make this less a hassle.

**Comment by Top-Ranger** [comment]
There should now be a more clear error message. This should resolve this issue.
